name: Deployment pipeline

env:
  MONGODB_URI: ${{ secrets.MONGODB_URI }}
  SECRET: ${{ secrets.SECRET }}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install 
        run: npm install && cd frontend && npm install
      - name: lint
        run: npm run lint && cd frontend && npm run lint
      - name: build
        run: cd frontend && npm run build && cp -r build ../build
      - name: test
        run: npm run test tests && cd frontend && npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start:prod && cd frontend
          wait-on: http://localhost:3000/
